### ISSUE TITLE
Across what dates was the poll conducted?

### ISSUE THREAD

**Issue by ShriSamson** [rethinkpriorities/rp_2020_benchmarking_poll#1]
Just asking out of curiosity and so this can be properly weighed against [previous](https://escholarship.org/uc/item/4cd2r446) [polls](https://www.ipsos.com/sites/default/files/ct/news/documents/2020-10/spectrum_multi-state_california_topline_102120_0.pdf). A quick search of '(1) Process Data.ipynb' looks like responses are from Oct 20-21st, does that look correct to you?

If so, here's an _addition_ to the 3rd sentance of the README to make it more explicit:

People from California were upsampled on Prolific _the dates October 20-21st_, so the raw data includes 1024 people from California and 3920 people from other US states. 

Thanks.

**Comment by peterhurford** [comment]
It was conducted entirely on October 20th. It says so in the second paragraph of the README and it is also in the writeups.
